# Generated by Django 3.1.5 on 2021-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='urlContent',
            field=models.URLField(max_length=500, null=True, verbose_name='UrlКонтент'),
        ),
        migrations.AddField(
            model_name='post',
            name='urlContent',
            field=models.URLField(max_length=500, null=True, verbose_name='UrlКонтент'),
        ),
    ]
