# Generated by Django 3.1.5 on 2021-01-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210109_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='urlContent',
        ),
        migrations.AddField(
            model_name='urlpost',
            name='titileImage',
            field=models.ImageField(null=True, upload_to='', verbose_name='Post Image'),
        ),
    ]
