# Generated by Django 3.1.5 on 2021-01-11 13:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20210109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='urlpost',
            name='titileImage',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Image'),
        ),
    ]
